services:
  back0:
    image: ghcr.io/marcioendo/rinha2025-back:v009
    command: ["0"]
    container_name: back0
    hostname: back0
    volumes:
      - /tmp:/tmp
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "125MB"

  back1:
    image: ghcr.io/marcioendo/rinha2025-back:v009
    command: ["1"]
    container_name: back1
    hostname: back1
    volumes:
      - /tmp:/tmp
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "125MB"

  front:
    image: ghcr.io/marcioendo/rinha2025-front:v009
    container_name: front
    hostname: front
    volumes:
      - /tmp:/tmp
    depends_on:
      - back0
      - back1
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "100MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
